/**
 * Write `public/sitemap.xml` from the routes the app actually answers to.
 *
 * SpotOn is one page that rewrites itself, so a crawler that does not execute
 * JavaScript sees a single URL where there are seventeen real pages. This is
 * how the rest of them get found — item A9 of the ad-readiness register, and
 * the reason it matters is traffic rather than compliance.
 *
 * **The routes are read out of `useRoute.ts` rather than typed again here.** A
 * URL is a promise, and a sitemap that promises one the app does not answer is
 * worse than no sitemap at all — it teaches a crawler to distrust the rest.
 *
 * Run: node tools/gen-sitemap.mjs — and re-run it whenever a route is added.
 */
import { readFileSync, writeFileSync } from "node:fs";

const ORIGIN = "https://playspoton.com";

const src = readFileSync(new URL("../src/lib/useRoute.ts", import.meta.url), "utf8");

const named = {};
for (const m of src.matchAll(/^const ([A-Z_]+) = "([^"]+)";/gm)) named[m[1]] = m[2];
const modes = [...src.matchAll(/^\s+\w+: "([a-z]+spotter)",/gm)].map((m) => m[1]);

const need = (key) => {
  const path = named[key];
  if (!path) throw new Error(`no ${key} in useRoute.ts — has a route been renamed?`);
  return path;
};

/**
 * What goes in, and what stays out.
 *
 * `/settings` is a real page and a pointless search result — it is three
 * toggles about this device, with nothing on it to find. The bench is left out
 * for the same reason and a stronger one: it is not for players. `/terms` is
 * written down rather than read, because it is the one page here whose route
 * is a plain string in `App` rather than a named constant.
 */
const pages = [
  "",
  need("DAILY"),
  need("LEADERBOARD"),
  need("HOME"),
  need("DUEL"),
  need("GAMES"),
  need("ABOUT"),
  need("FAQ"),
  need("CREDITS"),
  need("PRIVACY"),
  "terms",
  ...modes,
];

/** The front door first, then the shelves, then everything else. */
const priority = (p) =>
  p === "" ? "1.0" : ["home", "allgames", "about", "faq"].includes(p) ? "0.8" : "0.6";

const today = new Date().toISOString().slice(0, 10);
const body = pages
  .map(
    (p) => `  <url>
    <loc>${ORIGIN}/${p}</loc>
    <lastmod>${today}</lastmod>
    <priority>${priority(p)}</priority>
  </url>`,
  )
  .join("\n");

writeFileSync(
  new URL("../public/sitemap.xml", import.meta.url),
  `<?xml version="1.0" encoding="UTF-8"?>
<!-- AUTO-GENERATED by tools/gen-sitemap.mjs from the routes in
     src/lib/useRoute.ts. Do not edit by hand; re-run it when a route changes. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`,
);

process.stderr.write(`${pages.length} urls\n`);
